# Generated by Django 5.2.1 on 2025-06-03 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('hearing', 'Судебное заседание'), ('separate_hearing', 'Заседание по обособленному спору'), ('deadline', 'Срок подачи документов'), ('reminder', 'Личное напоминание')], max_length=20, verbose_name='Тип события')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания')),
                ('courtroom', models.CharField(blank=True, max_length=50, verbose_name='Номер зала/кабинета')),
                ('court_address', models.TextField(blank=True, verbose_name='Адрес суда')),
                ('participants', models.TextField(blank=True, verbose_name='Участники процесса')),
                ('agenda', models.TextField(blank=True, verbose_name='Вопросы для рассмотрения')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('postponed', 'Отложено'), ('completed', 'Проведено'), ('cancelled', 'Отменено')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('postponement_reason', models.TextField(blank=True, verbose_name='Причина отложения')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('telegram_notifications', models.BooleanField(default=False, verbose_name='Telegram уведомления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case', verbose_name='Дело')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('original_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postponed_events', to='calendar_events.calendarevent', verbose_name='Исходное событие')),
                ('separate_dispute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.separatedispute', verbose_name='Обособленный спор')),
            ],
            options={
                'verbose_name': 'Событие календаря',
                'verbose_name_plural': 'События календаря',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], max_length=20, verbose_name='Тип уведомления')),
                ('notification_time', models.CharField(choices=[('3_days', 'За 3 дня'), ('1_day', 'За 1 день'), ('2_hours', 'За 2 часа'), ('30_minutes', 'За 30 минут')], max_length=20, verbose_name='Время уведомления')),
                ('sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='calendar_events.calendarevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление о событии',
                'verbose_name_plural': 'Уведомления о событиях',
                'unique_together': {('event', 'user', 'notification_type', 'notification_time')},
            },
        ),
    ]
