# Generated by Django 5.2.1 on 2025-06-03 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='postponed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отложения'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='postponed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postponed_events', to=settings.AUTH_USER_MODEL, verbose_name='Кто отложил'),
        ),
        migrations.CreateModel(
            name='PostponementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_datetime', models.DateTimeField(verbose_name='Старая дата и время')),
                ('new_datetime', models.DateTimeField(verbose_name='Новая дата и время')),
                ('reason', models.TextField(blank=True, verbose_name='Причина переноса')),
                ('postponed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата переноса')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('new_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creation_logs', to='calendar_events.calendarevent')),
                ('original_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postponement_logs', to='calendar_events.calendarevent')),
                ('postponed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто перенес')),
            ],
            options={
                'verbose_name': 'Лог переноса события',
                'verbose_name_plural': 'Логи переносов событий',
                'ordering': ['-postponed_at'],
            },
        ),
    ]
