# Generated by Django 5.2.1 on 2025-06-03 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование суда')),
                ('court_type', models.CharField(choices=[('arbitration', 'Арбитражный'), ('general', 'Общей юрисдикции'), ('supreme', 'Верховный суд РФ'), ('constitutional', 'Конституционный суд РФ')], max_length=50, verbose_name='Тип суда')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Суд',
                'verbose_name_plural': 'Суды',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_case_number', models.CharField(max_length=100, verbose_name='Номер дела в суде')),
                ('case_type', models.CharField(choices=[('civil', 'Гражданское'), ('administrative', 'Административное'), ('criminal', 'Уголовное'), ('arbitration', 'Арбитражное'), ('bankruptcy', 'Банкротство')], max_length=50, verbose_name='Тип дела')),
                ('court_instance', models.CharField(choices=[('first', 'Первая инстанция'), ('appeal', 'Апелляционная'), ('cassation', 'Кассационная'), ('supervisory', 'Надзорная')], max_length=20, verbose_name='Инстанция')),
                ('subject_matter', models.TextField(verbose_name='Предмет спора')),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма требований')),
                ('case_status', models.CharField(choices=[('accepted', 'Принято к производству'), ('scheduled', 'Назначено к рассмотрению'), ('hearing', 'Рассматривается'), ('decided', 'Решение вынесено'), ('appeal_filed', 'Подана апелляция'), ('final', 'Вступило в силу'), ('execution', 'Исполнение'), ('closed', 'Дело закрыто')], max_length=20, verbose_name='Статус дела')),
                ('received_date', models.DateField(verbose_name='Дата поступления')),
                ('judge_name', models.CharField(max_length=200, verbose_name='Судья')),
                ('plaintiff', models.TextField(verbose_name='Истец/Заявитель')),
                ('defendant', models.TextField(verbose_name='Ответчик/Заинтересованное лицо')),
                ('third_party', models.TextField(blank=True, verbose_name='Третье лицо')),
                ('client_role', models.CharField(choices=[('plaintiff', 'Истец'), ('defendant', 'Ответчик'), ('third_party', 'Третье лицо'), ('other', 'Иное')], max_length=20, verbose_name='Роль представляемой стороны')),
                ('subcategory', models.CharField(blank=True, max_length=200, verbose_name='Подкатегория')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cases', to=settings.AUTH_USER_MODEL, verbose_name='Владелец дела')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.court', verbose_name='Суд')),
            ],
            options={
                'verbose_name': 'Дело',
                'verbose_name_plural': 'Дела',
                'unique_together': {('court_case_number', 'court')},
            },
        ),
        migrations.CreateModel(
            name='SeparateDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_name', models.CharField(max_length=500, verbose_name='Наименование спора')),
                ('court_determination_number', models.CharField(blank=True, max_length=100, verbose_name='Номер определения о выделении')),
                ('dispute_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма требований по спору')),
                ('plaintiff_dispute', models.TextField(verbose_name='Истец по спору')),
                ('defendant_dispute', models.TextField(verbose_name='Ответчик по спору')),
                ('dispute_status', models.CharField(choices=[('separated', 'Выделен'), ('scheduled', 'Назначен к рассмотрению'), ('hearing', 'Рассматривается'), ('decided', 'Решение вынесено'), ('closed', 'Завершен')], max_length=20, verbose_name='Статус спора')),
                ('dispute_description', models.TextField(blank=True, verbose_name='Описание спора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separate_disputes', to='cases.case', verbose_name='Основное дело')),
            ],
            options={
                'verbose_name': 'Обособленный спор',
                'verbose_name_plural': 'Обособленные споры',
            },
        ),
        migrations.CreateModel(
            name='CaseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('full', 'Полный доступ'), ('calendar', 'Только календарь'), ('view', 'Только просмотр')], max_length=20, verbose_name='Уровень доступа')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата предоставления')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='cases.case')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Предоставлен пользователем')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к делу',
                'verbose_name_plural': 'Доступы к делам',
                'unique_together': {('case', 'user')},
            },
        ),
    ]
