# Generated by Django 5.2.1 on 2025-06-03 08:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_type', models.CharField(choices=[('system', 'В систему'), ('case', 'К делу')], max_length=20, verbose_name='Тип приглашения')),
                ('invitee_email', models.EmailField(max_length=254, verbose_name='Email приглашаемого')),
                ('action', models.CharField(max_length=50, verbose_name='Действие')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата действия')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_history', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший')),
            ],
            options={
                'verbose_name': 'История приглашений',
                'verbose_name_plural': 'История приглашений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(max_length=254, verbose_name='Email приглашаемого')),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Токен приглашения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('used', 'Использовано'), ('expired', 'Истекло'), ('revoked', 'Отозвано')], default='pending', max_length=20, verbose_name='Статус')),
                ('expires_at', models.DateTimeField(verbose_name='Срок действия')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата использования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_system_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший (владелец системы)')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_system_invitation', to=settings.AUTH_USER_MODEL, verbose_name='Зарегистрированный пользователь')),
            ],
            options={
                'verbose_name': 'Приглашение в систему',
                'verbose_name_plural': 'Приглашения в систему',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(max_length=254, verbose_name='Email приглашаемого')),
                ('access_level', models.CharField(choices=[('full', 'Полный доступ'), ('calendar', 'Только календарь'), ('view', 'Только просмотр')], max_length=20, verbose_name='Уровень доступа')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('expired', 'Истекло')], default='pending', max_length=20, verbose_name='Статус')),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Токен приглашения')),
                ('invitation_message', models.TextField(blank=True, verbose_name='Сообщение при приглашении')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата приглашения')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('expires_at', models.DateTimeField(verbose_name='Срок действия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='cases.case', verbose_name='Дело')),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_case_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Приглашенный пользователь')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_case_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший')),
            ],
            options={
                'verbose_name': 'Приглашение к делу',
                'verbose_name_plural': 'Приглашения к делам',
                'ordering': ['-invited_at'],
                'unique_together': {('case', 'invitee_email')},
            },
        ),
    ]
